AlignParameters:
  Enabled: false

AsciiComments:
  Enabled: false

Encoding:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

LineLength:
  Max: 200

MethodLength:
  Max: 18

Naming/FileName:
  Enabled: false

Metrics/AbcSize:
  Max: 16

Style/RegexpLiteral:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false
